language: python
python:
    - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install pandoc -y
install:
    - "pip install -r requirements-dev.txt"
    - "pip install ."
script:
  - "flake8 --exclude=__init__.py prosperworks"
  - "tox"
